<<<<<<< HEAD
# Generated by Django 4.1 on 2022-09-05 19:47
=======
# Generated by Django 4.1.1 on 2022-09-09 15:19
>>>>>>> f9e98aee31d69df00198adf618c44dc96a640d60

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nobre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=20)),
                ('num_documento', models.CharField(max_length=20)),
                ('dirreccion', models.CharField(blank=True, max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_profesional', models.CharField(max_length=20)),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaapp.persona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_histial', models.IntegerField()),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('anamnesicos', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaapp.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaapp.veterinario')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='personas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaapp.persona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
