# Generated by Django 4.1 on 2022-09-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='veterinario',
            name='user',
        ),
    ]
