# Generated by Django 4.1.1 on 2022-09-19 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaapp', '0002_remove_cliente_user_remove_veterinario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='nobre',
            new_name='nombre',
        ),
    ]
